### ISSUE TITLE
Floated content

### ISSUE THREAD

**Issue by nickhamze** [sortabrilliant/spoiler-alert#4]
I missed this during testing but I noticed when I was putting together the marketing page that if I float an image or paragraph than Spoiler Alert fail to work.

Full width:
<img width="802" alt="screen shot 2018-12-01 at 10 27 06 pm" src="https://user-images.githubusercontent.com/158918/49335700-40844d00-f5b8-11e8-91de-dce014813e76.png">

Floated Right:
<img width="601" alt="screen shot 2018-12-01 at 10 26 56 pm" src="https://user-images.githubusercontent.com/158918/49335702-467a2e00-f5b8-11e8-873e-de37ca2d3512.png">

A floated paragraph:
<img width="830" alt="screen shot 2018-12-01 at 10 28 17 pm" src="https://user-images.githubusercontent.com/158918/49335712-71fd1880-f5b8-11e8-954b-172f62f9d102.png">

**Comment by jrtashjian** [comment]
Fixed. The issue was with the HTML generated for an image just added to a post and one that is floated. Fixing the class/element targeting in CSS resolved the issue.

![screenshot_2018-12-04 spoiler alert testing wordpress local](https://user-images.githubusercontent.com/375788/49458292-8b6db280-f7ba-11e8-83da-ca236299644e.png)
